### ISSUE TITLE
Error: Use of const in strict mode

### ISSUE THREAD

**Issue by FutureProg** [sindresorhus/emoj#7] opened 2016-06-24 03:40 UTC
When running the program I get the following in my terminal:

```
$ emoj --help
/usr/local/lib/node_modules/emoj/cli.js:3
const readline = require('readline');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

```
I'd just modify the code but I'm not sure if you put const there for a reason...

**Comment by sindresorhus** [comment] 2016-06-24 09:55
Duplicate of #1.

**Closed by sindresorhus** 2016-06-24 09:55 UTC
